export interface LessonMeta {
  day: number;
  title: string;
  description: string;
  keyMessage: string;
  duration: string;
  points: number;
  category: string;
  icon: string;
}

export const LESSONS: LessonMeta[] = [
  { day: 1,  title: 'The Plastic Crisis',           description: 'Discover how plastic pollution is devastating our oceans and wildlife.',         keyMessage: 'Every piece of plastic ever made still exists somewhere on Earth.',                                         duration: '5 min', points: 50,  category: 'plastic',    icon: '🥤' },
  { day: 2,  title: 'Paper and Forests',             description: 'Learn the connection between paper consumption and deforestation.',               keyMessage: 'Recycling one ton of paper saves 17 trees and 7,000 gallons of water.',                                      duration: '5 min', points: 50,  category: 'paper',      icon: '📄' },
  { day: 3,  title: 'E-Waste: The Hidden Danger',    description: 'Understand why electronic waste is the fastest growing waste stream.',           keyMessage: 'E-waste contains toxic materials that can leach into soil and water.',                                         duration: '6 min', points: 50,  category: 'e-waste',    icon: '💻' },
  { day: 4,  title: 'Composting Basics',             description: 'Turn your food scraps into black gold for gardens.',                             keyMessage: 'Composting reduces methane emissions from landfills by up to 50%.',                                          duration: '5 min', points: 50,  category: 'organic',    icon: '🍎' },
  { day: 5,  title: 'The Circular Economy',          description: 'Discover how recycling creates jobs and saves energy.',                          keyMessage: 'A circular economy could generate $4.5 trillion in economic benefits by 2030.',                                duration: '7 min', points: 50,  category: 'general',    icon: '♻️' },
  { day: 6,  title: 'Glass Recycling',               description: 'Learn how glass can be recycled endlessly without quality loss.',                keyMessage: 'Glass is 100% recyclable and can be melted and reformed indefinitely.',                                       duration: '5 min', points: 50,  category: 'glass',      icon: '🍶' },
  { day: 7,  title: 'Metal & Aluminum',              description: 'Discover why recycling aluminum saves 95% of the energy needed from ore.',       keyMessage: 'An aluminum can can be recycled and back on the shelf in 60 days.',                                          duration: '5 min', points: 50,  category: 'metal',      icon: '🥫' },
  { day: 8,  title: 'Textile Waste',                 description: "Explore fast fashion's environmental cost and how donation and recycling help.",  keyMessage: '92 million tonnes of textile waste is generated globally each year.',                                         duration: '6 min', points: 50,  category: 'textile',    icon: '👗' },
  { day: 9,  title: 'Hazardous Household Waste',     description: 'Understand batteries, paints, and chemicals — and how to dispose safely.',       keyMessage: 'One car battery can contaminate 25,000 litres of water if improperly disposed.',                              duration: '6 min', points: 50,  category: 'hazardous',  icon: '⚠️' },
  { day: 10, title: 'Ocean Plastic',                 description: "Discover Sri Lanka's coastline crisis and what marine wildlife is at stake.",     keyMessage: "Sri Lanka's coastlines are on the front line of the ocean plastic crisis.",                                  duration: '6 min', points: 50,  category: 'plastic',    icon: '🌊' },
  { day: 11, title: 'Climate Change & Waste',        description: 'Understand how waste contributes to 5% of global greenhouse gas emissions.',     keyMessage: 'Reducing waste is direct climate action — landfill methane is 80x worse than CO₂.',                           duration: '6 min', points: 50,  category: 'general',    icon: '🌡️' },
  { day: 12, title: 'Food Waste Economics',          description: "Explore the $1 trillion lost globally to food waste and Sri Lanka's challenge.", keyMessage: '1/3 of all food produced globally is wasted — worth $1 trillion per year.',                                    duration: '5 min', points: 50,  category: 'organic',    icon: '🍱' },
  { day: 13, title: 'Upcycling & Creativity',        description: "Turn waste into art — Sri Lanka's creative craftspeople show the way.",          keyMessage: 'Upcycling transforms waste into something of greater value than the original.',                                duration: '5 min', points: 50,  category: 'general',    icon: '🎨' },
  { day: 14, title: 'Corporate Responsibility',      description: 'Learn about EPR laws, plastic credits, and how brands are held accountable.',    keyMessage: 'Just 20 companies produce 55% of all single-use plastic waste globally.',                                     duration: '6 min', points: 50,  category: 'general',    icon: '🏢' },
  { day: 15, title: 'Zero Waste Lifestyle',          description: 'Discover the 5Rs — Refuse, Reduce, Reuse, Recycle, Rot — and minimalism.',      keyMessage: 'Zero waste is a direction, not a destination — the 5Rs are your guide.',                                      duration: '6 min', points: 50,  category: 'general',    icon: '🌿' },
  { day: 16, title: 'Biodegradable vs Compostable',  description: 'Understand the critical difference between these terms and greenwashing.',       keyMessage: '"Biodegradable" doesn\'t mean eco-safe — always check the infrastructure.',                                   duration: '5 min', points: 50,  category: 'general',    icon: '🌱' },
  { day: 17, title: 'Water & Waste Connection',      description: 'Learn how improper waste disposal threatens clean water in Sri Lanka.',          keyMessage: 'Proper waste disposal protects clean water — plastic in drains causes flooding.',                              duration: '5 min', points: 50,  category: 'general',    icon: '💧' },
  { day: 18, title: 'Wildlife & Waste',              description: "Discover how waste harms Sri Lanka's elephants, sea turtles, and marine life.",  keyMessage: 'Dozens of Sri Lankan elephants have died from ingesting plastic at open dumps.',                               duration: '6 min', points: 50,  category: 'general',    icon: '🐘' },
  { day: 19, title: 'Community Clean-up Culture',    description: 'Explore plogging, Shramadana, and how communities organize environmental action.', keyMessage: "Shramadana — Sri Lanka's tradition of voluntary labor — builds a cleaner environment.",                       duration: '5 min', points: 50,  category: 'community',  icon: '🤝' },
  { day: 20, title: 'Schools & Education',           description: 'Understand how teaching eco habits to children multiplies environmental impact.', keyMessage: 'Children who learn environmental habits in school maintain them for life.',                                    duration: '5 min', points: 50,  category: 'education',  icon: '📚' },
  { day: 21, title: 'Government & Policy',           description: 'Explore Sri Lanka\'s waste management laws and the role of local government.',   keyMessage: 'Policy shapes what\'s possible — but citizen demand shapes policy.',                                          duration: '6 min', points: 50,  category: 'general',    icon: '🏛️' },
  { day: 22, title: 'Technology & Recycling',        description: 'Discover how AI, robotics, and sensor tech are transforming recycling.',         keyMessage: 'AI-powered sorting can identify materials 100x faster than human sorters.',                                    duration: '6 min', points: 50,  category: 'general',    icon: '🤖' },
  { day: 23, title: 'Local Heroes',                  description: 'Meet Sri Lankan innovators and grassroots leaders fighting waste.',              keyMessage: 'Local action is the engine of global change — every hero starts in their community.',                          duration: '5 min', points: 50,  category: 'community',  icon: '🦸' },
  { day: 24, title: 'Your Eco Impact Report',        description: 'Reflect on your 24-day journey and see the real impact you have created.',       keyMessage: 'Your actions are not small — they are the beginning of something larger.',                                    duration: '7 min', points: 50,  category: 'general',    icon: '📊' },
  { day: 25, title: 'The Next Chapter',              description: 'Graduate as an Eco Scholar and build your personal sustainability manifesto.',   keyMessage: 'You are now an Eco Scholar. The planet needs you to keep going.',                                             duration: '10 min', points: 100, category: 'general',   icon: '🎓' },
];
